# Generated by Django 5.2.1 on 2025-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('text', models.TextField(max_length=2500, verbose_name='Текст')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Актуальна')),
            ],
            options={
                'verbose_name': 'Оферта',
                'verbose_name_plural': 'Оферта',
            },
        ),
    ]
