# Generated by Django 5.2.1 on 2025-06-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='name',
            field=models.CharField(default='1', max_length=200, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
