# Generated by Django 5.2.1 on 2025-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_oferta_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='oferta_file',
            field=models.FileField(blank=True, null=True, upload_to='oferta_files/', verbose_name='Файл'),
        ),
    ]
