# Generated by Django 5.2.1 on 2025-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveBigIntegerField(help_text='Фиксируется в момент оформления заказа', verbose_name='Цена'),
        ),
    ]
