# Generated by Django 5.2.1 on 2025-06-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('import_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='PriceMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('threshold', models.PositiveBigIntegerField(unique=True, verbose_name='Порог цены')),
                ('percent', models.FloatField(verbose_name='Процент наценки')),
            ],
            options={
                'verbose_name': 'Коэфициент наценки',
                'verbose_name_plural': 'Коэфиценты наценки',
                'ordering': ('threshold',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('code', models.CharField(max_length=150, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Описание')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('period_min', models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок мин')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальна')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул товара')),
                ('csv_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='import_goods.csvprice', verbose_name='Прайс-лист')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ('-is_actual', 'name', 'manufacturer__name'),
            },
        ),
    ]
