# Generated by Django 5.2.1 on 2025-06-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-is_actual', 'name'), 'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
    ]
