# Generated by Django 5.2.1 on 2025-06-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_published_alter_product_is_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_actual',
        ),
    ]
