# Generated by Django 5.2.1 on 2025-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_is_actual'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_per_csv',
        ),
        migrations.RemoveField(
            model_name='product',
            name='csv_price',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'code'), name='unique_product_per_csv'),
        ),
    ]
