# Generated by Django 5.2.1 on 2025-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_unique_product_per_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_qty',
            field=models.PositiveIntegerField(blank=True, help_text='если min_qty = 2, то order_qty может быть равен 2, или 4, или 8, и т.д.', null=True, verbose_name='Минимальное количество "min_qty"'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.CharField(blank=True, null=True, verbose_name='Доступно для заказа'),
        ),
    ]
