# Generated by Django 5.2.1 on 2025-05-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('url', models.URLField(help_text='Пример: https://example.ru/media/pricelist_n398.csv', verbose_name='Путь к файлу для скачивания')),
            ],
            options={
                'verbose_name': 'Прайс поставщика',
                'verbose_name_plural': 'Прайсы поставщиков',
            },
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('run_at', models.TimeField(verbose_name='Время запуска')),
                ('active', models.BooleanField(default=True, verbose_name='Включена')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('prices', models.ManyToManyField(related_name='tasks', to='import_goods.csvprice', verbose_name='Прайсы')),
            ],
            options={
                'verbose_name': 'Задача импорта',
                'verbose_name_plural': 'Задачи импорта',
            },
        ),
    ]
