# Generated by Django 5.2.1 on 2025-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('drop_by_words', models.BooleanField(default=False, help_text='Столбец будет учитываться при удалении по словам', verbose_name='Удаление по словам')),
            ],
            options={
                'verbose_name': 'Столбец в прайсе',
                'verbose_name_plural': 'Столбцы в прайсах',
            },
        ),
        migrations.CreateModel(
            name='CSVPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('url', models.URLField(help_text='Пример: https://example.ru/media/pricelist_n398.csv', verbose_name='Путь к файлу для скачивания')),
                ('period_min', models.PositiveSmallIntegerField(default=1, help_text='Оставит детали со "Срок мин" равные или больше указанного значения', verbose_name='Фильтр по "Срок мин"')),
                ('new_period_min', models.PositiveSmallIntegerField(default=0, help_text='Переназначит у всех деталей "Срок мин", если указано больше 0.', verbose_name='Новый "Срок мин"')),
                ('price_filter', models.FloatField(default=0, help_text='Оставит детали где "Цена" больше или равна указанному значению', verbose_name='Фильтр по цене')),
            ],
            options={
                'verbose_name': 'Прайс поставщика',
                'verbose_name_plural': 'Прайсы поставщиков',
            },
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('run_at', models.TimeField(verbose_name='Время запуска')),
                ('active', models.BooleanField(default=True, verbose_name='Включена')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущена')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Задача импорта',
                'verbose_name_plural': 'Задачи импорта',
            },
        ),
        migrations.CreateModel(
            name='WordToDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Слово для удаления',
                'verbose_name_plural': 'Слова для удаления',
            },
        ),
    ]
