# Generated by Django 5.2.1 on 2025-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('import_goods', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvprice',
            name='ignored_manufacturers',
            field=models.ManyToManyField(blank=True, related_name='ignored_in_prices', to='products.manufacturer', verbose_name='Фильтр по производителям'),
        ),
        migrations.AddField(
            model_name='importtask',
            name='prices',
            field=models.ManyToManyField(related_name='tasks', to='import_goods.csvprice', verbose_name='Прайсы'),
        ),
    ]
