# Generated by Django 5.2.1 on 2025-05-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующий запуск'),
        ),
    ]
