# Generated by Django 5.2.1 on 2025-06-07 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('import_goods', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('level', models.CharField(choices=[('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка'), ('DEBUG', 'Отладка')], default='INFO', max_length=10, verbose_name='Уровень')),
                ('message', models.TextField(max_length=3000, verbose_name='Сообщение')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Лог ипорта',
                'verbose_name_plural': 'Логи импорта',
            },
        ),
    ]
