# Generated by Django 5.2.1 on 2025-06-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_goods', '0003_csvimportlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvimportlog',
            options={'verbose_name': 'Лог импорта', 'verbose_name_plural': 'Логи импорта'},
        ),
    ]
