# Generated by Django 5.2.1 on 2025-06-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbot',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +71234567890 или 89123456789', regex='^(?:\\+7|8)\\d{10}$')]),
        ),
    ]
