name: Deploy on remote server

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo '--- START WORK ON REMOTE SERVER ---'
          cd ${{ secrets.PROJECT_FOLDER }}
          echo '--- LIST OF FILES ---'
          ls -al
          echo '--- GIT INFORMATION ---'
          git checkout main
          git pull origin main --force
          echo '--- DOCKER OPERATIONS ---'
          docker compose down
          echo '--- LIST OF DOCKER CONTAINERS AFTER STOPING DOCKER CONTAINERS ---'
          docker ps
          docker compose up -d --build
          docker system prune --all --force
          echo '--- LIST OF DOCKER CONTAINERS AFTER STARTING DOCKER CONTAINERS ---'
          docker ps
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Деплой autozakaz успешно выполнен!